### ISSUE TITLE
Module 'ldbus' not found

### ISSUE THREAD

**Issue by hrqmonteiro** [Sewdohe/Nvim-Adapt#1]
I am trying to use it and i get an error:

```
Error detected while processing /home/minutrade/.config/nvim/init.lua:
E5113: Error while calling lua chunk: ...vim/site/pack/packer/start/nvim-adapt/lua/nvim-adapt.lua:8: module 'ldbus' not
found:
        no field package.preload['ldbus']
        no file './ldbus.lua'
        no file '/home/minutrade/neovim/.deps/usr/share/luajit-2.1.0-beta3/ldbus.lua'
        no file '/usr/local/share/lua/5.1/ldbus.lua'
        no file '/usr/local/share/lua/5.1/ldbus/init.lua'
        no file '/home/minutrade/neovim/.deps/usr/share/lua/5.1/ldbus.lua'
        no file '/home/minutrade/neovim/.deps/usr/share/lua/5.1/ldbus/init.lua'
        no file './ldbus.so'
        no file '/usr/local/lib/lua/5.1/ldbus.so'
        no file '/home/minutrade/neovim/.deps/usr/lib/lua/5.1/ldbus.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        ...vim/site/pack/packer/start/nvim-adapt/lua/nvim-adapt.lua:8: in function 'init'
        ...vim/site/pack/packer/start/nvim-adapt/lua/nvim-adapt.lua:109: in main chunk
        [C]: in function 'require'
        /home/minutrade/.config/nvim/init.lua:6: in main chunk
Press ENTER or type command to continue

```

![Screenshot from 2022-07-17 13-36-37](https://user-images.githubusercontent.com/17055027/179413086-c7fe64bd-b6fe-4a17-b21a-45c3d1448de0.png)

**Comment by Sewdohe** [comment]
I'm sorry I forgot about this issue before uploading.  What OS are you on?

You see that file path it's not finding? When I get back to my PC I'll send you a link to the .so file needed 

It's needed because the dbus lib this plugin uses isn't compatible with neovims JIT Lua compiler. I had to manually build the libs .so file

So if you're on Linux I'll send you the one I already built, if not I'll have to post build instructions for you to build that lib for your system

**Comment by Sewdohe** [comment]
Try throwing this shared object file into `/usr/lib/lua/5.1/` folder and see if the plugins runs then
[ldbus.zip](https://github.com/Sewdohe/Nvim-Adapt/files/9128382/ldbus.zip)

make sure to un-zip it. Github wouldn't let me upload the .so file

**Comment by Sewdohe** [comment]
So I'm going to have to build ldbus for each system architecture and load the correct one based on the system. Fix should be coming soon - ldbus will be included in the plugin
